### ISSUE TITLE
TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by hasan-araav** [azuddin/maybank-todo#1]
I tried to run the app but's it's showing TypeError: Only absolute URLs are supported. Help me to fix it pls.

**Comment by azuddin** [comment]
have you created the `.env` file?

**Comment by hasan-araav** [comment]
There was on doc abt it and i don't see any on codebase. Can u share the format?

**Comment by azuddin** [comment]
just copy the file `.env.local.example` to `.env.local`

**Comment by hasan-araav** [comment]
now it's showing this error 

**error - FetchError: invalid json response body at http://localhost:3000/todo?slug=RCD6C1 reason: Unexpected token < in JSON at position 0**

**Comment by azuddin** [comment]
then `backend` need to be run prior serving the code.

**Comment by hasan-araav** [comment]
too much complicated bro, thank anyway
